language: python

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=docs
  - TOXENV=check-manifest
  - TOXENV=checkreadme
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36

before_install:
  - pip install codecov # for coverage

install:
  - pip install tox

script:
  - tox

after_success:
  - codecov
